### ISSUE TITLE
Unable to install jupyter-jvm-basekernel

### ISSUE THREAD

**Issue by THTony** [SpencerPark/IJava#11]
Hello, I am learning Java recently and decide to use familiar Jupyter Notebook. I followed the README file to install "jupyter-jvm-basekernel". However, when I downloaded the whole project and tried to build it, my terminal sent this:
```powershell
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.
```

My environment is Win10 with Java JDK 9.0.4
```powershell
> java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
How can I fix it?

**Comment by SpencerPark** [comment]
Oops didn't mean to close just yet...

[https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457](https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457) seems to describe the problem and it looks to be a gradle bug that was fixed later on.

I tried updating the wrapper to `4.2.1` over there. Please confirm and we can make the change here as well.

**Comment by THTony** [comment]
Oops, wrong close again...
The "jupyter-jvm-basekernel" built itself pretty fine. Thanks.
However, Ijava could not build yet. So, I tried to copy the "gradle" folder, "gradlew.bat" and "gradlew" from the "jupyter-jvm-basekernel" folder to Ijava folder. Then, I built the Ijava successfully but can't run the kernel in Jupyter Notebook.  It seems I still need you to update Ijava repository.

**Comment by SpencerPark** [comment]
> The "jupyter-jvm-basekernel" built itself pretty fine. However, Ijava could not build yet.

Great, thanks! The change is now propagated to IJava as well.

> Then, I built the Ijava successfully but can't run the kernel in Jupyter Notebook. It seems I still need you to update Ijava repository.

Make sure that to install the kernel you are running `gradlew installKernel` in the `IJava` clone directory.

Once you have confirmed it's all working, please close this and thank you for reporting this issue and helping to get it fixed!

**Comment by THTony** [comment]
It is working perfectly now. Thanks.
