### ISSUE TITLE
How to give JDK path to IJava kernel ?

### ISSUE THREAD

**Issue by fbuloup** [SpencerPark/IJava#12]
Hello,

I'm trying to run IJava kernel on Win7 without admin privilege. There is already a default JDK 8 installed in the system. I've copied JDK 9 folder in my home folder, checking JShell application is present. But when I launch Jupyter notebook and try to start Java kernel, I get this Exception :

> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/spencerpark/ijava/IJava hasbeen compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Meaning that IJava is trying to use system JDK 8. 
Unfortunatlely, I don't know how to tell IJava kernel where to get proper JDK.

Is there a way to give JDK path to IJava Kernel configuration ?

Thanks,
Frank

**Comment by SpencerPark** [comment]
Hello Frank,

There are 2 options:

1.  Edit the `kernel.json`.
    *   Execute `jupyter kernelspec list` to find the install directory of the kernel.
        ```
        Available kernels:
          java           C:\Users\Spencer\.ipython\kernels\java
         ...
        ```
    *   In that directory find `kernel.json` and change `argv`. The `kernel.json` is somewhat like a configuration file that tells jupyter how to start the kernel. The `argv` is simply a command to execute. **NOTE:** use `/` or when using `\` you must escape them in JSON by writing `\\` instead. 
        ```diff
        {
            "argv": [
        -        "java",
        +       "C:/absolute/path/to/jdk-9/bin/java"
                "-jar",
                "C:/Users/Spencer/.ipython/kernels/java/ijava-1.0.6-SNAPSHOT.jar",
                "{connection_file}"
            ],
            ...
        }
        ```

2.  Add java 9 temporarily to your path before starting the notebook.
    *   Like mentioned above the kernel just executes the `java` command to start up the kernel. This means that we can stick the more recent java version at the front of your path.
    *   `set PATH=C:\absolute\path\to\jdk-9\bin\;%PATH%` will do this.
        *   As a side note I have some variables `JAVA7_HOME`, `JAVA8_HOME`, `JAVA9_HOME` to simplify this switch. Then I use `set PATH=%JAVA9_HOME%\bin\;%PATH%` to use a certain version.
    *   Then when using `where java` it may give multiple paths but the one at the top of the list should be java 9. 
    *   Finally launch the notebook with this new path and you should be good to go. Putting everything together
        ```
        set PATH=%JAVA9_HOME%\bin\;%PATH% && jupyter notebook
        ```

Please let me know how things go!

**Comment by fbuloup** [comment]
Hello !

Thanks a lot for your detailed response.

I've been able to configure and launch IJava using both solutions. The first solution is probably the fastest while the other one is probably the most flexible.

Thank you.

**Comment by MaximeJo** [comment]
Hi @SpencerPark and @fbuloup,

I am using Anaconda and had the same problem with my JDK version.
The built-in version of JDK that comes with Anaconda seems to be OpenJDK 1.8.0_152.

I've tried both methods mentioned by @SpencerPark but none of them seem to work for me.
Here is an extract of my `kernel.json` file.
`{`
`"argv": [`
`        "java",`
`		"D:\\JDKs\\jdk-11.0.2\\bin\\java",`
`        "-jar",`
`        "D:\\Programs\\Anaconda3\\share\\jupyter\\kernels\\java/ijava-1.2.0.jar",`
`        "{connection_file}"`
`],`
`    ...`
`}`
I have tried changing the `\\` to `/` or shortening the path (I don't have a `java` directory in my `path_to_sdk/bin`).
I also tried different JDK versions but whenever I launch `jupyter console --kernel=java` I always end up with the following error:

> Impossible to find or load main class D:\JDKs\jdk-11.0.2\bin\java

Is there something I am missing here ?
Thanks,
Max

**Comment by SpencerPark** [comment]
Hi Max, the full path to your java installation should replace the first `"java"` from the `"argv"` list. So that first `"java",` line should be removed. i.e.

```diff
{
"argv": [
-"java",
"D:\\JDKs\\jdk-11.0.2\\bin\\java",
"-jar",
"D:\\Programs\\Anaconda3\\share\\jupyter\\kernels\\java/ijava-1.2.0.jar",
"{connection_file}"
],
...
}
```

The `"argv"` is the command that jupyter runs to start the kernel so you can test that `D:\\JDKs\\jdk-11.0.2\\bin\\java -jar D:\\Programs\\Anaconda3\\share\\jupyter\\kernels\\java/ijava-1.2.0.jar` runs (but gives the expected error for the missing connection file). If you can run that without any errors about missing modules/classes then everything should be good to go with `jupyter console --kernel=java`.

**Comment by MaximeJo** [comment]
Thank you very much SpencerPark, I got it working !

I guess I should have read your original post more carefully...

**Comment by SpencerPark** [comment]
@MaximeJo, no worries. Glad it's working!
