### ISSUE TITLE
Issue with reading user input

### ISSUE THREAD

**Issue by Poonna** [SpencerPark/IJava#14]
Hi again,

I've been trying to get user input on Jupyter Notebook without success. I'm not sure what the problem is, but the code here:

```java
import java.util.Scanner;

Scanner input = new Scanner(System.in);
String s = input.next();
System.out.println(s);
```

produced this error:

```
---------------------------------------------------------------------------
java.util.NoSuchElementException: 
	at java.base/java.util.Scanner.throwFor(Scanner.java:858)
	at java.base/java.util.Scanner.next(Scanner.java:1381)
	at .(#19:1)
```

If I used `input.nextLine()` instead, I got a `No line found` error:

```
---------------------------------------------------------------------------
java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1554)
	at .(#19:1)
```

I tried switching to BufferedReader:

```java
import java.io.BufferedReader;
import java.io.InputStreamReader;

BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
String s = reader.readLine();
System.out.println(s);
```

which resulted in:

```
null
```

I wonder if there's a way to get this to work. Please let me know if I could be of any help.

Thanks,
Poonna

**Comment by SpencerPark** [comment]
Hi Poonna, thank you for the issue. It is really helpful to see what other users are trying to do with the kernel. There is a quick fix on both projects relating to this but before updating the basekernel I'd like to get things published if this can wait a bit longer!

**Comment by Poonna** [comment]
Sorry for not replying earlier. Just a note to express my gratitude that your IJava kernel has been a tremendous help in my lecture note writing during the past month. Thanks for your great work!

**Comment by SpencerPark** [comment]
> Just a note to express my gratitude that your IJava kernel has been a tremendous help in my lecture note writing during the past month. Thanks for your great work!

Thank you! I'm glad to hear you are getting good use out of the kernel!

As for the issue it should be fixed now but please let me know if you are still running into problems.

**Comment by ncc-74205** [comment]
This still seems not to work properly. Following code:
`import java.util.Scanner;
Scanner s = new Scanner(System.in);
System.out.print("Enter: ");
String str = s.next();
System.out.println(str.toUpperCase());`

I don't seem to get out of the input - every time I hit Enter, a new input textfield is displayed and the code does not reach the final System.out.println. I'm using MacOS.
