### ISSUE TITLE
Can't use wildcards in IJAVA_CLASSPATH option

### ISSUE THREAD

**Issue by erlendviggen** [SpencerPark/IJava#17]
I'm using IJava to explore some Java libraries that I want to familiarise myself with, and it's working out really well for me so far. However, I came upon a minor issue when pointing the IJava classpath to multiple libraries in multiple .jar files stored in the same directory.

Explicitly pointing to the individual .jar files in kernel.json works perfectly:

`"IJAVA_CLASSPATH" : "/path/to/lib/Lib1.jar:/path/to/lib/Lib2.jar:/path/to/lib/Lib3.jar"`

However, it is possible to use wildcards in Java classpaths to point to multiple .jar files in one directory. For example, this works for me when launching `jshell`:

`jshell --class-path "/path/to/lib/*"`

However, if I try to similarly use a wildcard in kernel.json, 

`"IJAVA_CLASSPATH" : "/path/to/lib/*"`

then IJava reports that it does not work:

```
|   import path.to.class.ClassName;
package path.to.class does not exist
```

It's a small issue with an easy workaround (explicitly pointing to all the libraries), but I thought I'd report it regardless.

**Comment by SpencerPark** [comment]
Quick update on whats happening here. The path matcher I referenced before didn't actually have any support for finding files, only checking if they match. But I promised glob so we've got something close which I think covers the majority of the use cases anyways (especially the one you have listed). It's essentially the classpath rules plus patterns with `*` and `?` as well as matching a directory.

The supported seemed general enough that I moved it to the base kernel which means that this will be merged once the work on `mime-rendering` is done (which I am aiming for this week).

**Comment by SpencerPark** [comment]
Alright @erlendviggen it's on master now (along with some other exciting changes). Please close this after you've had a chance to check things out and see if they are what you were looking for. Thanks!

**Comment by erlendviggen** [comment]
The wildcard style I had in my original report now works perfectly! Thanks a lot.

**Comment by clerk-populous** [comment]
the answer was hiding here https://fringed22.github.io/iIP7i4mBPnM/
