### ISSUE TITLE
Build fails due to plugin com.github.hierynomus.license not found

### ISSUE THREAD

**Issue by HelderGualberto** [SpencerPark/IJava#20]
The error is
FAILURE: Build failed with an exception.

* Where:
Build file '/IJava/build.gradle' line: 4

* What went wrong:
Plugin [id: 'com.github.hierynomus.license', version: '0.14.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.hierynomus.license:com.github.hierynomus.license.gradle.plugin:0.14.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by damonmerrill** [comment]
I got the same error on the first try, but upon trying the same gradle installKernel command a second time, it worked.

**Comment by SpencerPark** [comment]
Apologies for the late reply on this but hopefully the gradle build will not be necessary any longer with the packaged release. 

Please post the result of running with the `--stacktrace` option so we can get a better idea of why it fails. Additionally the output from `gradlew --version` may be benifical to narrowing down any affected versions of gradle and/or java if it happens to be something out of our control.  

The plugin is indeed in the gradle central plugin repository https://plugins.gradle.org/m2/com/github/hierynomus/license/com.github.hierynomus.license.gradle.plugin/0.14.0/ so it must be an issue with reaching it (likely more issues around https which have been poping up quite a bit lately).

**Comment by HelderGualberto** [comment]
Thank You @SpencerPark for the reply and the new release. Its working fine now!

**Comment by SpencerPark** [comment]
Closing as it doesn't appear to be an issue anymore.
