### ISSUE TITLE
variables not explicitely initialized cause internal error

### ISSUE THREAD

**Issue by nherbaut** [SpencerPark/IJava#24]
![image](https://user-images.githubusercontent.com/960823/44346673-d3302e80-a496-11e8-9a55-b6cff1f6fe77.png)

**Comment by SpencerPark** [comment]
Thanks for the report. I will try to fix a couple of the currently open issues and create a new release.

**Comment by nherbaut** [comment]
thanks!

**Comment by nherbaut** [comment]
confirmed fixed by 1.1.2, thanks!
