### ISSUE TITLE
SPIResolutionException leaks to the user

### ISSUE THREAD

**Issue by SpencerPark** [SpencerPark/IJava#29]
Running a cell with an undefined (potentially forward) reference inside a method raised an SPIResolutionException.

```java
void test(Object o) {
    System.out.println(obj); // a typo, meant 'o'
}
test("IJava");
```

results in

```text
jdk.jshell.spi.SPIResolutionException: resolution exception
	at .test(#44:1)
	at .(#45:1)
```

Unfortunately this exception is not very informative, nor does it contain much information as presented by JShell.

**Comment by CSchoel** [comment]
The students in my course also encountered this error quite often and as you say the error message is not very helpful. I think it would be best if you could produce a warning message similar to the one that the JShell itself shows for that statement.

```
jshell> void test(Object o) {
   ...>     System.out.println(obj); // a typo, meant 'o'
   ...> }
|  created method test(Object), however, it cannot be invoked until variable obj
 is declared

jshell> test("IJava");
|  attempted to call method test(Object) which cannot be invoked until variable
obj is declared
```

I also think for beginners it is especially important to see that the *definition* of the Method already has a problem.

**Comment by SpencerPark** [comment]
The case mentioned in the original issue is now handled well. The secondary issue about immediate feedback for undefined (potentially forward) references is not because of the notion of a "cell" which jshell doesn't have.

In a notebook, a single execution may define multiple methods that together define all the required references and the intermediate execution of each statement shouldn't make any mention of the temporary issue. The other thing is that when writing a notebook it is perfectly natural to execute these things top down meaning the definition is already typed below but not yet executed in which case a warning about the forward reference is just too verbose. It really only makes sense in the console context which makes it hard to justify supporting this behavior.
