### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by adibaba** [SpencerPark/IJava#30]
Is there a way to use Java assertions?

Using a Python3 kernel and the line:
```
assert(1==2)
``` 
an AssertionError is returned:
```
AssertionErrorTraceback (most recent call last)
<ipython-input-2-000000000000> in <module>()
----> 1 assert(1==2);

AssertionError:
``` 

Using the IJava kernel and the same line, there is no return value or exception displayed.

**Comment by SpencerPark** [comment]
Assertions in java are a bit different, there is the `assert` keyword but it is disabled by default. To enable it the `-ea` flag must be passed in the jvm arguments. In the IJava kernel this can be done by editing the `kernel.json` and adding the `-ea` flag to the `argv` list but this makes your notebooks less reproducible as users would require the same setup.

What I would recommend is use a library like [junit assertions](https://github.com/junit-team/junit4/wiki/Assertions) which are common in java unit testing and easily included with the maven magic. 

Run a cell with the following to include all of the `assert` methods from junit to the static space in your notebook:

```java
%maven junit:junit:4.12
import static org.junit.Assert.*;
```

Use the assertion methods like the following:

```java
assertTrue("Assertion message", 1 == 1);
assertTrue(1 == 2);
```

which is the same as the following pure java code **if -ea is enabled**:

```java
assert 1 == 1: "Assertion message";
assert 1 == 2;
```

**Comment by adibaba** [comment]
Thank you so much for your answer!

(In parallel to your message (aka the last minutes) I found the -ea approach, too.
https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html#enable-disable
https://github.com/SpencerPark/IJava#changing-vmcompiler-options
But your suggestion of using jUnit sounds very good, maybe better.
Thanks for your fast response & support!)

**Comment by hkarl** [comment]
So I tried this via the maven / junit approach. This works fine in a notebook, and the notebook does show Assertions being thrown nice (see screenshot below). However, that still leads to nbgrader to assign full credit. Basically, what nbgrader does, is to look at the msg_type and looks for the `error` type. 

https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbbase.py#L55

This seems fairly straightforward, so I am tempted to think there is something amiss in how IJava and kernel / nbgrader communicate such exception. Could you perhaps give a pointer where to look for this interaction in the IJava code? 

Thanks a bundle! 

![image](https://user-images.githubusercontent.com/1374616/45843055-cebd9680-bd1e-11e8-84af-6dfcf1ae83d3.png)

**Comment by SpencerPark** [comment]
@hkarl I see a lot of value in ensuring that the kernel works well with nbgrader as one of my favorite things about jupyter is how nice it is for teaching.

The meat and potatoes of the protocol details is in a different project [jupyter-jvm-basekernel](https://github.com/SpencerPark/jupyter-jvm-basekernel) which I wanted to keep more general as I plan on writing kernels for some other jvm based languages in the future. You can find more details there specificall in the [BaseKernel.java](https://github.com/SpencerPark/jupyter-jvm-basekernel/blob/master/src/main/java/io/github/spencerpark/jupyter/kernel/BaseKernel.java) which is what the java kernel extends. 

If you see `handleExecuteRequest` it does in fact reply with an error on the shell channel and an error on iopub as well. I double check by looking at the `Network` tab in chrome dev tools, restart the kernel, filter by `WS`, select the channel?... and look at the `Frames` tab. This should show you all the messages that come over the notebook-jupyter_client socket. Furthermore you can type `iopub` in the filter to just see things going over iopub.

In running your code the browser received the following message:

```json
{
  "header": {
    "msg_id": "2b85c09a-587e-429f-8b61-6d79cfe46b8e",
    "username": "username",
    "session": "b6f3c34cdfa1448d918d3a0f3b03df2e",
    "date": "2018-09-20T20:20+0000",
    "msg_type": "error",
    "version": "5.0"
  },
  "msg_id": "2b85c09a-587e-429f-8b61-6d79cfe46b8e",
  "msg_type": "error",
  "parent_header": {
    "msg_id": "acf345b801a444b88e27d60b5e92f548",
    "username": "username",
    "session": "b6f3c34cdfa1448d918d3a0f3b03df2e",
    "date": "2018-09-20T20:20:30.914537Z",
    "msg_type": "execute_request",
    "version": "5.2"
  },
  "metadata": { },
  "content": {
    "ename": "EvalException",
    "evalue": "null",
    "traceback": [
      "\u001b[1m\u001b[31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1m\u001b[31mjava.lang.AssertionError: null\u001b[0m",
      ...
    ]
  },
  "buffers": [ ],
  "channel": "iopub"
}
```

when I download the notebook and look in the `outputs` for the cell it also has

```json
    {
     "ename": "EvalException",
     "evalue": "null",
     "output_type": "error",
     "traceback": [
      "\u001b[1m\u001b[31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1m\u001b[31mjava.lang.AssertionError: null\u001b[0m",
      ...
     ]
    }
```

**Comment by hkarl** [comment]
Thanks. I can reproduce that, looks plausible to me, and currently trying to debug the flow of this information through nbgrader. Somehow, somewhere, there is  a difference between python and java notebook. (Also compare: https://github.com/jupyter/nbgrader/issues/986#issuecomment-423431795 ). 

Thanks a bundle; will keep this posted in case we solve this.

**Comment by SpencerPark** [comment]
@hkarl I see on the referenced comment things might appear to be working as expected? I would appreciate an update on how the interaction is going with IJava and nbgrader in either case and your experience writing autograder tests. If there is anything I can help with, kernel side or writing java libraries intended for grading with the kernel, I would be more than happy to get some work going on that. Thanks!

**Comment by hkarl** [comment]
Thanks for following up! Current preliminary testing seems to indicate it works. It will get its main workout when we  run >400 students and their homeworks through it in December :-) - we will keep you posted.
