### ISSUE TITLE
Kernel Interrupts Fail (can't stop long running commands)

### ISSUE THREAD

**Issue by aramadia** [SpencerPark/IJava#33]
I have a simple cell with

`
for (int i = 0; i < 20; i++) {
  System.out.println(i);
  Thread.sleep(1000);
}
`

I hit the interrupt button in Jupyter expecting it will interrupt the command.
However the cell runs to completion and prints this in the console output:

[I 13:47:24.582 NotebookApp] Kernel interrupted: bcb8133c-58d3-4727-911c-2fca4dc40d5b
Sep 20, 2018 1:47:24 PM io.github.spencerpark.jupyter.channels.ShellChannel lambda$bind$16
SEVERE: Unhandled message: none

**Comment by SpencerPark** [comment]
Support for interrupts should be available on master and will be in the next release.

**Comment by SpencerPark** [comment]
Now in release [1.2.0](https://github.com/SpencerPark/IJava/releases/tag/v1.2.0).
