### ISSUE TITLE
Kernel logo artwork

### ISSUE THREAD

**Issue by misja** [SpencerPark/IJava#40]
Thanks so much for creating this kernel, it already has been invaluable for use in introductory Java classes.

I'd like to contribute some logo artwork which will show up as a kernel icon when used in notebook mode. This works quite simple, if the kernel installation directory contains ``logo-32x32.png`` and ``logo-64x64.png`` then it will be used in the notebook interface. I'm not seeing any install related code in this repository (e.g. ``install.py``) to which I could contribute so am for now including the icons in this issue?
![logo-64x64](https://user-images.githubusercontent.com/36168/47261263-77e8df80-d4cb-11e8-9864-d354e9a4ae54.png)
![logo-32x32](https://user-images.githubusercontent.com/36168/47261264-77e8df80-d4cb-11e8-9324-7316c01300ea.png)

Adding a screenshot to show how this addition could make it look more polished:
![kernel_logo](https://user-images.githubusercontent.com/36168/47261443-e760ce00-d4cf-11e8-99e5-5f26efb930b6.png)

**Comment by SpencerPark** [comment]
Hello @misja, thank you very much for the artwork! It is always great to hear that it is being used for teaching, that is very motivating for me. The images should go in a `kernel` directory at the top level of the project and the gradle plugin will package it in the distribution.

The only thing I am worried about is if we are allowed to use the java logo. I was looking into this in the past but it fell off my radar. See the related document http://www.oracle.com/us/technologies/java/java-licensing-logo-guidelines-1908204.pdf especially the section on the colors we are supposed to use for the blue and orange.

 I've sent an email asking about this and will update when I hear back.

**Comment by misja** [comment]
Oh of course, I should have known there could be licensing issues ... Thanks for looking into this, for now just dropping updated logos here which confirm to the guideline document.

![logo-64x4](https://user-images.githubusercontent.com/36168/47312213-05e3d800-d63c-11e8-80c2-6e4bc8c104fa.png)
![logo-32x32](https://user-images.githubusercontent.com/36168/47312233-109e6d00-d63c-11e8-852c-81dfe05eaa7d.png)

**Comment by SpencerPark** [comment]
I received a reply from Oracle asking for more information. I've sent some screenshots using the new logos provided and sent those files as well. Will update again if there is any more information.

**Comment by SpencerPark** [comment]
Alright so I followed up on this and the reply is that if we are testing with the Oracle TCK then we can use the java logo, otherwise we can use the Duke logo which is open source.

I know it has been a while and therefore totally understand if you are no longer interested but I am not sure what to do now. I'm not really a fan Duke and was really hoping to be able to use the coffee one but I don't think the effort of constantly testing against the TCK (not even sure how to go about that) is worth it. Possibly we go with a Duke variation? There are some files https://hg.openjdk.java.net/duke/duke/file/e71b60779736 we can use/work from. Or also something completely different.

Any suggestions?

**Comment by misja** [comment]
Hi @SpencerPark revisiting and closing this issue. Thanks for the effort you put into getting in touch with Oracle. The dissapointing answer was to be expected and although a logo would have been a nice touch, I would like to suggest we just just leave it as is for now ...
