### ISSUE TITLE
Allow installing in any directory

### ISSUE THREAD

**Issue by dclong** [SpencerPark/IJava#43]
Currently one must run `python3 install.py --sys-prefix` in the directory containing `install.py` to install the package. It makes things a little bit easier if we can installing the package by specifying the absolute path of `install.py`.

**Comment by SpencerPark** [comment]
Hi @dclong, underneath that install script uses the same API as jupyter's kernelspec app. You can use `--sys-prefix` but also supported is `--user` and `--prefix` options. See `python3 install.py -h` for more info on those. 

`--user` will install to the per user jupyter data dir. `--prefix` allows specifying a location (intended to be a conda prefix but is not a requirement) in which the kernel is installed in `PREFIX/share/jupyter/kernels/`. These might be enough for your use case but I do also see the benefit of specifying some arbitrary directory.

I'll open up an issue in the gradle plugin repo which is what generates the script but we can keep this open for tracking. Thanks!

**Comment by dclong** [comment]
@SpencerPark Thank you for your quick response. I'm asking to support installing IJava by running the following command in a directory that is the parent directory of `install.py`.
```
python3 /path_to/install.py --sys-prefix
```

**Comment by SpencerPark** [comment]
Ah, my apologies, I read things too fast. Regardless we might get a new feature from the installer out of it :) This issue makes even more sense now and is definitely something that needs fixing. I would consider this a bug. Thanks.

**Comment by SpencerPark** [comment]
Alright this is fixed in the installer plugin and updated here. As of the next release the installer will be able to be run from anywhere as you have suggested `python3 /path_to/install.py --sys-prefix`.

We can keep this open until then.
