### ISSUE TITLE
Cannot import class files from package in classpath

### ISSUE THREAD

**Issue by erlendviggen** [SpencerPark/IJava#45]
I am writing a Java package that I would like to experiment with in IJava. I have compiled it and put it in a folder that we can call `/path/to/package/` for the sake of the example. More specifically, if my Java package name is `example.package.name`, there are some class files in the folder `/path/to/package/example/package/name/`.

For jshell, it works well to make my package available through the classpath argument:

`jshell --class-path "/path/to/jars/*:/path/to/package"`

This way, I can import and use packages from the .jar files in in `/path/to/jars/` and my own package in `/path/to/package/`.

I am trying to get the same classpath to work in IJava with the following environment argument in kernel.json:

`"IJAVA_CLASSPATH": "/path/to/jars/*:/path/to/package"`

While this successfully lets me import packages from the .jar files like jshell does, it does not let me import my own package. Instead, the statement `import example.package.name.*` results in an error

`|   import example.package.name.*;`
`package example.package.name does not exist`

Could this be a bug or a missing feature in IJava?

**Comment by SpencerPark** [comment]
Thanks for the report. I will try to reproduce and debug this when I get a chance (most likely this weekend). Just to confirm, you are on some unix system? Also when you run `System.getenv("IJAVA_CLASSPATH")` in a notebook that fails with the error you are talking about, it still outputs `/path/to/jars/*:/path/to/package`?

**Comment by erlendviggen** [comment]
I just checked, and I can confirm that `System.getenv("IJAVA_CLASSPATH")` outputs exactly what I input in kernel.json, which is on the form `/path/to/jars/*:/path/to/package`.

I can also give you some details on my setup:
* macOS 10.13.6
* Python 3.6.6 (Anaconda distribution)
* Jupyter 1.0.0
* IJava 1.2.0 (this problem also existed on 1.1.0)

**Comment by SpencerPark** [comment]
Alright I can confirm this is a bug. The glob changes from 1.1.0 which tried to resolve files only, I hadn't considered adding a directory as adding a directory that contained a jar didn't work. This needs a quick change upstream in the basekernel and then should be no problem to fix here.

**Comment by SpencerPark** [comment]
SpencerPark/jupyter-jvm-basekernel@58b3e5b1c88327569ea52feac5b669b7d59c0711 supports this, the difference between matching files and paths has been made explicit. The classpath should match paths, but for backwards compatibility `%jars` should probably stick to files with a new magic for adding a local package.
