### ISSUE TITLE
Loading jsh files

### ISSUE THREAD

**Issue by GiovanniGatti** [SpencerPark/IJava#52]
Hello,

I would like to know the current policy for loading jsh files when running Jupyter Notebook cells with IJava. 

In jshell we can do:

```bash
$ jshell 
|  Welcome to JShell -- Version 11.0.2
|  For an introduction type: /help intro

jshell> /open test.jsh

jshell> test();
hello
```

In IPython loading Python scripts is quite straightforward, all we need to do is to use the magic `%load <python.py>`, but I couldn't find any way to do the same within IJava environment.

I think that it is generally a good idea to be able to hide boilerplate code within a Jupyter Notebook and I think that this is an important feature to add (if it is not yet available).

If no workaround is available, I'm willing to contribute.

Thank you,

**Comment by SpencerPark** [comment]
Thanks for the issue @GiovanniGatti! This sounds like a great feature and certainly makes sense to include in the next release (which I've been slacking on recently). Should be a straight forward magic to add and makes sense to include.

The only question is `%load` or `%open`? Do we want to align more with IPython or jshelltool? I'm nervous to imply that all jshell commands have an associated magic as that is not the intention but also want to make the transition back and forth between jshell and ijava as painless as possible.

**Comment by GiovanniGatti** [comment]
> The only question is %load or %open?
IMHO any choice you make is the right one (as long it is well documented). I am slightly more `load` than `open` for the same reason as you ("transition back and forth between jshell and ijava as painless as possible").

> all jshell commands have an associated magic
I do agree with you that it seams mostly a bad idea. Unless real use cases come up in the future, most of jshell commands looks like useless outside jshell itself (specially if you are running a notebook is a real IDE). I think that you should let it clear in the documentation.
