### ISSUE TITLE
How to import the functions and static variables from another .ipynb file?

### ISSUE THREAD

**Issue by BoyuanYan** [SpencerPark/IJava#54]
Hi everybody. If I want to implement some functions in a .ipynb file, and invoke these functions in another .ipynb file, is there any way to do that? 
I saw "%run" or "%load" work with Python kernel, but not in IJava kernel.

Thanks a lot.

**Comment by SpencerPark** [comment]
Hi @BoyuanYan, I misunderstood this as a duplicate of #52 but it is really an extension of it to also work with notebooks.

Currently implementing it in the base kernel and will have this available under `%load` as well. Thanks for the suggestion!

**Comment by SpencerPark** [comment]
Support landed in SpencerPark/jupyter-jvm-basekernel@114023d314554fbb9d0c0992eb740abcaa679a6c and so we will get this in IJava in next release.

**Comment by BoyuanYan** [comment]
Got it. Thanks for your response.
