### ISSUE TITLE
Use JDK13 only for IJava.

### ISSUE THREAD

**Issue by 157492196** [SpencerPark/IJava#75]
My computer was installed JDK13, and IJava can be installed in this env. But I have to change my env to JDK8, so the IJava do not work. Hence, I want to set path of JDK13 to IJava, what should I do?

**Comment by SpencerPark** [comment]
Hi @157492196, good question. The kernel will pick up the environment variables/PATH from the `jupyter` process which means whatever version is setup in the shell that runs `jupyter notebook` should be the one that IJava is using. This means you can make the appropriate change in jdk just before running `jupyter notebook` by putting the desired `java` binary on your `%PATH%`.

Of course if this is for your personal installation, you can edit the `kernel.json` to tell IJava exactly what jdk to use everytime. Check out option 1 in this comment to a similar issue https://github.com/SpencerPark/IJava/issues/12#issuecomment-361405202 and please let me know if that helps with your setup.

**Comment by 157492196** [comment]
It is work for me, thank you. #12
