### ISSUE TITLE
Support maven dependency references at runtime

### ISSUE THREAD

**Issue by SpencerPark** [SpencerPark/IJava#9]
Notebooks should be able to bring in maven dependencies at runtime since we are able to change the classpath (this may wipe the state but there is no harm if they run at the start).

The interface for this can be through the magics.

**Comment by robchallen** [comment]
Have you seen this project:

https://github.com/kawasima/try-artifact

As far as I can make out it creates a wrapper around JShell extending it with a /resolve command that picks up maven artifacts. I've tested it out and works fine, and it would be nice to include it in a jupyter notebook. Looking through both sets of code I can't quite see how to do it but feels like it should be possible.

**Comment by SpencerPark** [comment]
Very happy to report this is now supported as of f1cf0c68809d3621b343534e257f3d59fd9d0db2. I ended up using https://github.com/shrinkwrap/resolver. 

Simply using `%maven group:artifact:version` should grab the dependency and add it to the notebook classpath. See also [magics.md](https://github.com/SpencerPark/IJava/blob/7f5aa9ab858859a010fd228364b080606399ae60/docs/magics.md) for more information on that.

**Comment by robchallen** [comment]
Nice. Will take a look.
