### ISSUE TITLE
couldn't install your kernel 

### ISSUE THREAD

**Issue by YousefSaber** [SpencerPark/IJava#92]
``` 
joseph@joseph-X541UJ:~/Downloads/ijava-1.3.0$ ls
install.py  java
joseph@joseph-X541UJ:~/Downloads/ijava-1.3.0$ python3 install.py --sys-prefix
install.py:169: DeprecationWarning: replace is ignored. Installing a kernelspec always replaces an existing installation
  replace=args.replace
Traceback (most recent call last):
  File "install.py", line 169, in <module>
    replace=args.replace
  File "/home/joseph/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.7/shutil.py", line 324, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'
joseph@joseph-X541UJ:~/Downloads/ijava-1.3.0$ sudo python3 install.py --sys-prefix
Traceback (most recent call last):
  File "install.py", line 6, in <module>
    from jupyter_client.kernelspec import KernelSpecManager
ModuleNotFoundError: No module named 'jupyter_client'
joseph@joseph-X541UJ:~/Downloads/ijava-1.3.0$ 
```
please help me how to install the kernel ? 

Jupyter-client is also installed on my system 
```
joseph@joseph-X541UJ:~/Downloads/ijava-1.3.0$ python3 -m pip show jupyter-client
Name: jupyter-client
Version: 5.3.4
Summary: Jupyter protocol implementation and client libraries
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /home/joseph/.local/lib/python3.7/site-packages
Requires: tornado, pyzmq, traitlets, jupyter-core, python-dateutil
Required-by: qtconsole, octave-kernel, notebook, jupyter-console, ipyparallel, ipykernel
```

**Comment by YousefSaber** [comment]
sorry with this command I could successfully install it 
```
 jupyter kernelspec install --user  java/
```

**Comment by sharmila02** [comment]
I am currently facing the same error, If I leave it like that I am not getting any output
![image](https://user-images.githubusercontent.com/66949552/97984521-e243f280-1dfc-11eb-860c-ad069b6386e9.png)
If I follow your command 
`jupyter kernelspec install --user  java/`
kernel is not connecting at all.

**Comment by YousefSaber** [comment]
@YousefSaber 
just run `HelloWorld.main(null)`
![image](https://user-images.githubusercontent.com/33742499/98061588-dd129200-1e54-11eb-844f-4d89fe92f4cc.png)

**Comment by kqvanity** [comment]
After fiddling for a bit of time with the `IJava` kernel, i've had an adjustment at the `kernel` configuration file, which can be found as a `json` file located at the corresponding kernel path obtained from the `jupyter kernelspec list` command. I've tweaked the `ijava` jar file path, which was an `argv` array element. As for me, the initial path was prefixed with `@KERNEL_INSTAll_DiRECTORY@` which i've got substituted with the file's absolute path.
Generally, I find it odd, as consecutive kernel installations got the absolute path down, without manual intervention on my side. Any how, you can try either removing the `java kernel` using `jupyter kernelspec remove java` or removing its directory itself, then reinstalling it at the home directory using `pythone some-IJava-release/install.py --user`
